---
title: "Portfolio"
---

This Page is dedicated to the various class projects, public projects done for employers, and personal projects.

### Projects 

#### Big Data (DSAN 6000) Final Project
[Link to Deliverable](https://gu-dsan6000.github.io/fall-2024-project-team-29/) | [Github](https://github.com/gu-dsan6000/fall-2024-project-team-29) | December 2024

Summary: We created a website that had exploratory data analysis, natural language processing, and machine learning aspects all applied to a 100 GB dataset of reddit data. For this project I specifically found a subset of the data where US States were mentioned, created visualizations of this dataset, found the sentiment associated with each state, and created a machine learning model to predict the score of the post based on all the variables.

#### Natural Language Processing (DSAN 5800) Final Project
[Link to Deliverable](https://docs.google.com/presentation/d/1GzWrOpMp3qInxHbbkDERY1NzALd6HCGF4lNTFvmB8g8/edit?usp=sharing) | [Github](https://github.com/msheeba4848/Framework-Insight-Retrieval-and-Summarization-) | December 2024

Summary: For this project we created a presentation and report (which is in the github) on the use of various retrieval augmented generation (RAG) methods which had the goal of finding cases relevant to a search. Large Language models normally have a problem with hallucinating results and RAG is a method to sidestep that issue.

#### Election Night Dashboard
[Link to Deliverable](https://bluebonnetdata-powell.shinyapps.io/Mecklenburg_Forecasting/) | [Github](https://github.com/powellres/Mecklenburg_County_Election_Night_Dashboard) | November 2024

Summary: A Dashboard made in R for the Mecklenburg County Democrats in Charlotte, NC. We were working with them in 2024 during the election and they wanted a way to review their results and compare them to the 2020 and 2022 election seasons. The Dashboard was made in R using Shiny and Plotly to make the interactive graphs.

#### Returning Student Scholarship 
[Link to Deliverable](https://powellres.github.io/Powell-Returning-Student-Scholarship/) | [Github](https://github.com/powellres/Powell-Returning-Student-Scholarship) | June 2024

Summary: When entering the second year of my two year program they gave the students a chance to compete for a merit-based scholarship through projects we make and our contributions to the program. We submitted a project based on soil water retention data from a study on Natural Bridges National Park. I submitted my project and won the second highest prize for my work.

#### Nueral Networks (DSAN 6600) Final Project
[Link to Deliverable]() | [Github]() | May 2024

Summary: For this group project we took a dataset of item from Amazon (found on Kaggle) which had price and an image of the product. We fit a convolutional neural network to the images in order to predict the price of the product itself. In this process we transformed and permutated the original images to better train the model. We were midly successful with interesting results that the model tended to look at logos or other branding for information about price.

#### Analytics for Statistical Learning (DSAN 5300) Final Project
[Link to Deliverable](https://docs.google.com/presentation/d/1mPTNj81_li8VuwGgmnVuQ4IFktSMeM-T/edit#slide=id.p1) | [Github](https://github.com/IrnT/5300FinalProject) | May 2024

Summary: On this group project

#### Data Visualization (DSAN 5200) Final Project
[Link to Deliverable]() | [Github](https://github.com/gu-dsan5200/spring-2024-dsan-5200-project-repo-project-group-13-1) | May 2024



#### Intro to Statistics (DSAN 5100) Final Project
[Link to Deliverable](https://powellres.github.io/DSAN5100-Final-Project-Powell/report/report.html) | [Github](https://github.com/powellres/DSAN5100-Final-Project-Powell) | December 2023

#### DSAN 5000 Final 
[Link to Deliverable](https://powellres.github.io/DSAN5000-final-project-Powell/) | [Github](https://github.com/powellres/DSAN5000-final-project-Powell) | December 2023

Summary: For this project, we were asked to pick a dataset and apply a variety of machine learning methods. I chose a public knitting database on which I cleaned the data;performed exploratory data analysis; used analysis techniques like Naive Bayes Predictive modeling, Clustering, Dimensionality Reduction, and Decision trees/Random forests; and concluded the results all while documenting my code.

#### Political Science Comprehensive
[Link to Deliverable]() | [Github]() | Date

### Papers

#### Principal Components of Happiness
[Link to the paper](https://www.sciencedirect.com/science/article/pii/S1757780224003755)

Summary: In this article oublished in Regional Science Policy and Practice we disscus a novel use of Principal Componenet Analysis to index wellbeing in Mexico in a method that contrasted the leading economic measures. This was a project started in a workshop in 2020 through the CIMAT summer system and involved a presentation in the 61st annual conference of the Western Regional Science Association.

### Articles

#### The Swarthmore Phoenix 
[This links to all of the articles](https://swarthmorephoenix.com/author/powell_sheagren/) I wrote for the Swarthmore Phoenix while I was a staff writiter there. I wrote for the Campus Journal, Opinions, and Arts section. The wriritng didn't overlap as much with my academic interests but I was happy to contribute to the periodical periodically.

#### Legacy Dilemma
Interviewed by the New York Times for an article on [Legacy in the context of the end of Affirmative Action](https://www.nytimes.com/2023/07/30/us/politics/legacy-admissions-college-alumni.html).



#### Five Global Health Priorities for the future President
While Interning for the Friends of the Global Fight I helped write [this article](https://www.the-american-interest.com/2020/07/20/five-global-health-priorities-for-the-next-president/) published by Ambassador Mark Lagon in the American Interest
